name: Javascript Tests

on: [push]

jobs:
  test:
    name: Cyprus run
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        machines: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1